sudo: required
dist: trusty
language: node_js
node_js:
- '8'
env:
  global:
    - BROWSER_STACK_USERNAME: bugsnagplatforms1
    - secure: "X29QA8LjTZL9RHnoiYlprpIbv264e//KjL3Q4A/vWZ8QbIRD2MY8w9wuIfQEYHLGa7kf1EAGPoH/Ka3raj7s5+J4hOeCeMC0ZWUWdAem35FE7zGm8wJrCKFK5GD9LF+1LRxK+gBfKfeaJkwcbjv7tl0DEW1JNC9PS4cpI0DRJzM="
  matrix:
    - BROWSER=ie_8
    # - BROWSER=ie_9
    # - BROWSER=ie_10
    # - BROWSER=ie_11
    # - BROWSER=edge_14
    # - BROWSER=edge_15
    # - BROWSER=safari_5
    - BROWSER=safari_10
    # - BROWSER=opera_47
    # - BROWSER=opera_48
    # - BROWSER=iphone_4s
    - BROWSER=android_s8
    # - BROWSER=firefox_30
    - BROWSER=firefox_56
    # - BROWSER=chrome_43
    - BROWSER=chrome_61
addons:
  browserstack:
    username: bugsnagplatforms1
    access_key:
     secure: "lB2aZc0HzuinyhSJyP98lzDJTbZsroEOJTrS/flnLLsHb/C096zjhwkWexHnfmNIPaY5SB2FF0G6zcnknlmsXg5TgxQiK7bdyJmkcAetGi+cSKnGaBq7GZXVhbWh++MRnddQDGV6jrSr7aqrWf85ncq3L4//9BTV6uAhDBWu2bo="
