sudo: required
dist: trusty
language: node_js
node_js:
  - '10'
before_install:
  - npm i -g npm@5.3.0
  - gem install bundler -v 1.16.1
install:
  - bundle install
  - npm install
before_script:
  - npm run build
script:
  - bundle exec maze-runner
env:
  global:
    - BROWSERSTACK_USERNAME: bugsnagplatforms1
    - secure: "tt/Rk4trBHP2+776EQPmpInHXGWojZYGLpvm2KPjw6Wb+PzK+bJiVoox2PZ1tfKl834CxpPa8yJK26Bh1/qgxf0cNOC9cY2QyLJCIOCVAMPQ0jhNj4l9ouOe+MfA0cHpOLb91rKtRcwF6YSZ5sHVG3bF1Jk51Q8drMmTqj/GHYk="
  matrix:
    - BROWSER=ie_8
    # - BROWSER=ie_9
    # - BROWSER=ie_10
    # - BROWSER=ie_11
    # - BROWSER=edge_14
    # - BROWSER=edge_15
    # - BROWSER=safari_5
    - BROWSER=safari_10
    # - BROWSER=opera_47
    # - BROWSER=opera_48
    # - BROWSER=iphone_4s
    - BROWSER=android_s8
    # - BROWSER=firefox_30
    - BROWSER=firefox_56
    # - BROWSER=chrome_43
    - BROWSER=chrome_61
addons:
  browserstack:
    username: bugsnagplatforms1
    access_key:
     secure: "lB2aZc0HzuinyhSJyP98lzDJTbZsroEOJTrS/flnLLsHb/C096zjhwkWexHnfmNIPaY5SB2FF0G6zcnknlmsXg5TgxQiK7bdyJmkcAetGi+cSKnGaBq7GZXVhbWh++MRnddQDGV6jrSr7aqrWf85ncq3L4//9BTV6uAhDBWu2bo="
